//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vehicle_clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseTbl
    {
        public int purchaseTbl_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public byte[] email { get; set; }
        public byte[] order_note { get; set; }
        public Nullable<int> contact { get; set; }
        public string email2 { get; set; }
    }
}
