//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vehicle_clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public Nullable<int> role { get; set; }
        public string display_order { get; set; }
        public string created_at { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
